Exercices XP

In [ ]:
# Exercice 1 : Création et manipulation de tableaux

import numpy as np

array_1D = np.arange(10)
print(array_1D)


[0 1 2 3 4 5 6 7 8 9]


In [6]:
#Exercice 2 : Conversion de type et opérations sur les tableaux

ma_list = [3.14, 2.17, 0, 1, 2]

list_numpy = np.array(list).astype(int)
print(list_numpy)

[3 2 0 1 2]


In [10]:
#Exercice 3 : Travailler avec des tableaux multidimensionnels

array_3D = np.arange(1, 10).reshape(3, 3)
print(array_3D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Exercice 4 : Création d'un tableau multidimensionnel avec des nombres aléatoires
import random 

array_2D = np.random.random((4, 5))
print(array_2D)

[[0.18651817 0.95678252 0.15147449 0.90595919 0.04705926]
 [0.61188697 0.82815253 0.09343286 0.71616437 0.79589103]
 [0.42140746 0.22736753 0.52762476 0.29398156 0.13465683]
 [0.08961015 0.40859611 0.89864915 0.01367875 0.87220179]]


In [23]:
#Exercice 5 : Indexation des tableaux

array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print(array[1])

[20 21 22 23 24]


In [36]:
#Exercice 6 : Inversion des éléments

array_inv = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
print(array_inv[::-1])

[0 1 2 3 4 5 6 7 8 9]


In [43]:
#Exercice 7 : Matrice identité

array_iden = np.eye(4)
print(array_iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [49]:
#Exercice 8 : Fonctions agrégées simples

array_sum = np.arange(10)
sum = array_sum.sum()

moy = array_sum.mean()

print("The sum :", sum)
print("The Moy :", moy)


The sum : 45
The Moy : 4.5


In [50]:
#Exercice 9 : Créer un tableau et modifier sa structure

array_nmp = np.arange(1, 21).reshape(4, 5)
print(array_nmp)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [55]:
#Exercice 10 : Sélection conditionnelle des valeurs

array_numpy = np.array([1, 3, 5, 7, 9])
array_imp = array_numpy[array_numpy % 2 != 0 ]
print(array_imp)


[1 3 5 7 9]
